#! /bin/bash
mkdir /home/pi/.config/lxsession
mkdir /home/pi/.config/lxsession/LXDE-pi
cp /etc/xdg/lxsession/LXDE-pi/autostart /home/pi/.config/lxsession/LXDE-pi/
cp /home/pi/kiscellli/autostart/chromium/autostart /home/pi/.config/lxsession/LXDE-pi/

