#! /bin/bash

echo "Megváltoztattad a videó nevét a motion_sensor.py - ban vagy a video.service -ben? (igen|nem)"
read ready
if [ "$ready" = "nem" ]; then
    exit 0
fi
sudo apt install -y $(cat packages.txt)
# Shutdown button
sudo cp /home/pi/kiscelli/services/shutdown_btn.service /etc/systemd/system
sudo chmod +x /etc/systemd/system/shutdown_btn.service
sudo chmod +x /home/pi/kiscelli/shutdown/shutdown_btn.py
sudo systemctl enable shutdown_btn.service

echo "Szeretnéd telepíteni a mozgásérzékelőt? (igen|nem)"
read motion
if [ "$motion" = "igen" ]; then
    # Motion sensor
    /home/pi/kiscelli/autostart/python/setup
    echo "Mozgásérzékelő telepítve"
fi

echo "Szeretnéd telepíteni a videólejátszót? (igen|nem)"
read play
if [ "$play" = "igen" ]; then
    # Video play
    /home/pi/kiscelli/autostart/video/setup
    echo "Videólejátszó telepítve"
fi

echo "Szeretnéd telepíteni a torztükröt? (igen|nem)"
read tukor
if [ "$tukor" = "igen" ]; then
    # Torztükör
    /home/pi/kiscelli/autostart/chromium/setup
    echo "Torztükör telepítve"
fi

echo "Szeretnéd újraindítani a málnát? (igen|nem)"
read restart
if [ "$restart" = "igen" ]; then
    # Reboot
    sudo reboot
fi

exit 0